PREFIX : <https://purl.org/homerent/>
PREFIX schema: <http://schema.org/>
PREFIX gr: <http://purl.org/goodrelations/v1#>


SELECT ?rentalAd ?rentalAdId
WHERE {
    ?rentalAd :rentAdCode ?rentalAdId ;
              gr:includes ?apartment .
    ?apartment schema:address ?address .
    ?address :geoName <https://sws.geonames.org/3178957/> .
}
